### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by jez**
Thanks for all your work on Intero for Neovim; it's quite a great project!
When I was first getting started with it, I had a lot of questions that I could
only find out by browsing the source. That's usually a good sign to add
documentation :sweat_smile:

Commit summary:

- **Add online help (`:help intero`)**

  Intero deserves a fancy help file! It makes the project look more
  attractive to new users. Also contains answers to a bunch of questions I
  had when first starting out.

- **Update README**

  With the new help doc, we probably don't wan to duplicate documentation too
  much. But, we still want the README to be useful.

  This new README has the essentials for a casual GitHub browser, and defers
  to the documentation for everything else.

  Also, has a fancy new screencast!

**Also**: I know preferences about documentation can get personal; I'm completely open to suggestions.

### CODE REVIEW

**Comment by parsonsmatt** [comment]
I'm loving the asciicast. The new README is great. Thanks for all the work you've done here!

**Comment by rdnetto** [comment]
This is awesome! One nit: can we keep the CI badge on the README? It doesn't take up much space, and gives a good impression of our code quality.

**Comment by jez** [comment]
> It doesn't take up much space, and gives a good impression of our code quality.

Good call! I only removed it at first because Travis hadn't been enabled for the repo. Looks like that changed recently, so I've added it back in.

**Comment by parsonsmatt** [comment]
@rdnetto Since your concern was addressed, I am going to merge this.

Thanks @jez ! :smile:

**Pull request merged**
